# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laraUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AtishUi(object):
    def setupUi(self, AtishUi):
        AtishUi.setObjectName("AtishUi")
        AtishUi.resize(1932, 1000)
        self.centralwidget = QtWidgets.QWidget(AtishUi)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -70, 1931, 1061))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\DELL\\OneDrive\\Desktop\\LARA\\Images\\FINALBACK.gif"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1060, 270, 411, 141))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\DELL\\OneDrive\\Desktop\\LARA\\Images\\INITI.gif"))
        self.label_2.setObjectName("label_2")
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1370, 910, 541, 81))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:\\Users\\DELL\\OneDrive\\Desktop\\LARA\\Images\\loaDING.gif"))
        self.label_3.setObjectName("label_3")
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1150, 180, 281, 91))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\DELL\\OneDrive\\Desktop\\LARA\\Images\\LARA.png"))
        self.label_4.setObjectName("label_4")

        
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(1150, 50, 241, 51))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border -radius:none;\n")
        self.textBrowser.setObjectName("textBrowser")

        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(1570, 50, 241, 51))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border -radius:none;\n")
        self.textBrowser_2.setObjectName("textBrowser_2")


        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1450, 740, 141, 141))
        self.pushButton.setText("")

        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\DELL\\OneDrive\\Desktop\\LARA\\Images\\MikePNG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(200, 200))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1680, 740, 141, 141))
        self.pushButton_2.setText("")

        
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\DELL\\OneDrive\\Desktop\\LARA\\Images\\stopMike.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_2.setObjectName("pushButton_2")

        
        self.label.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        AtishUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(AtishUi)
        QtCore.QMetaObject.connectSlotsByName(AtishUi)

    def retranslateUi(self, AtishUi):
        _translate = QtCore.QCoreApplication.translate
        AtishUi.setWindowTitle(_translate("AtishUi", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AtishUi = QtWidgets.QMainWindow()
    ui = Ui_AtishUi()
    ui.setupUi(AtishUi)
    AtishUi.show()
    sys.exit(app.exec_())
